name = "Barn2 Starter App"
scopes = "read_products,write_products,write_script_tags"

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topic = "app/uninstalled"
uri = "/webhooks/uninstalled"

[[webhooks.subscriptions]]
topic = "customers/data_request"
uri = "/webhooks/customers/data_request"

[[webhooks.subscriptions]]
topic = "customers/redact"
uri = "/webhooks/customers/redact"

[[webhooks.subscriptions]]
topic = "shop/redact"
uri = "/webhooks/shop/redact"
